-- VOAS AI — V2 Sprint 3 WhatsApp integration schema.
-- Adds workspace-level WhatsApp AI config + per-location Twilio WhatsApp config.
-- Mirrors the voice schema (00005) but WhatsApp replies are generated by our
-- own OpenAI call rather than Vapi; Twilio is only the message transport.

------------------------------------------------------------
-- whatsapp_settings (one row per workspace)
------------------------------------------------------------

create table public.whatsapp_settings (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  system_prompt text not null default '',
  greeting text not null default 'Hi! How can I help you today?',
  model text not null default 'gpt-4o-mini',
  enabled boolean not null default false,
  session_window_hours int not null default 24,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_whatsapp_settings_updated_at
  before update on public.whatsapp_settings
  for each row execute function public.set_updated_at();

------------------------------------------------------------
-- location_whatsapp_config (one row per location, null = not configured)
------------------------------------------------------------

create table public.location_whatsapp_config (
  id uuid primary key default gen_random_uuid(),
  location_id uuid not null references public.locations(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  twilio_account_sid text not null,
  twilio_auth_token text not null,                -- TODO: encrypt at rest before customer launch
  twilio_whatsapp_number text not null,           -- E.164, e.g. +14155238886 (sandbox) or production sender
  enabled boolean not null default true,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(location_id)
);

create index idx_location_whatsapp_workspace on public.location_whatsapp_config(workspace_id);
create index idx_location_whatsapp_phone on public.location_whatsapp_config(twilio_whatsapp_number);

create trigger trg_location_whatsapp_updated_at
  before update on public.location_whatsapp_config
  for each row execute function public.set_updated_at();

------------------------------------------------------------
-- RLS
------------------------------------------------------------

alter table public.whatsapp_settings enable row level security;
alter table public.location_whatsapp_config enable row level security;

create policy "members read whatsapp settings"
  on public.whatsapp_settings for select using (public.is_workspace_member(workspace_id));

create policy "owners manage whatsapp settings"
  on public.whatsapp_settings for all
  using (public.is_workspace_owner(workspace_id))
  with check (public.is_workspace_owner(workspace_id));

create policy "members read whatsapp config"
  on public.location_whatsapp_config for select using (public.is_workspace_member(workspace_id));

create policy "owners manage whatsapp config"
  on public.location_whatsapp_config for all
  using (public.is_workspace_owner(workspace_id))
  with check (public.is_workspace_owner(workspace_id));
